# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 446335ea9155123c1bdda234f091715d23cc41d09985239a294a3fa61ebe163cc8ce5ccaf3ff4b524756cbd4bf3ef564eb3042465ad97de4321d367299416f3f

test:
  secret_key_base: 76c5d1d51e4bac09b44c7564aaf20714066cf016c6a477cac30c870367abf7ded7ff0a35648a9c7d60f20620f8509e0005deaded2a9e606d98c0f9efaad6f232

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
